// <auto-generated />
namespace CBApplication.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class loan23 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loan23));
        
        string IMigrationMetadata.Id
        {
            get { return "201909231135490_loan23"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
